ALTER TABLE projects
ADD COLUMN IF NOT EXISTS show_prices BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS show_sold_prices BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS show_sqm BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS whatsapp_number VARCHAR(50),
ADD COLUMN IF NOT EXISTS enable_public_quotes BOOLEAN DEFAULT false;
